scheduleListCountSql = '''
    SELECT COUNT(DISTINCT A.TURBINE_ID) FROM 
        (SELECT * FROM
            ( SELECT ROW_NUMBER () OVER ( PARTITION BY TURBINE_ID ORDER BY DATA_TYPE DESC ) FLAG, ST.* FROM {search_table} ST) 
        WHERE FLAG = 1) A
    LEFT JOIN TURBINE_MASTER_TABLE TM ON A.COUNTRY_CD = TM.CODE
    LEFT JOIN OUTAGE_SCHEDULE C on A.TURBINE_ID = C.TURBINE_ID
    WHERE 1=1
    {and_sql}
'''

scheduleListSql = '''
    SELECT * FROM (
    SELECT A.KHN_PLANT_CD AS PLANT_CD, NVL(A.PLANT_NAME_EN, A.PLANT_NAME_JP) AS PLANT_NAME,
        TM.DATA1 AS COUNTRY_NM, A.TURBINE_ID,A.DATA_TYPE, C.OUTAGE_START, C.OUTAGE_END, C.TEIKEN_ID, C.DELETE_FLG,
        LEAST(NVL(C.OUTAGE_TYPE_T, 999), NVL(C.OUTAGE_TYPE_G, 999)) as COLOR_NUMBER,
        DENSE_RANK() OVER(ORDER BY A.TURBINE_ID, LEAST(NVL(C.OUTAGE_TYPE_T, 999), NVL(C.OUTAGE_TYPE_G, 999)) DESC) IDX
    FROM 
     (SELECT * FROM ( 
     SELECT ROW_NUMBER () OVER ( PARTITION BY TURBINE_ID ORDER BY DATA_TYPE DESC ) FLAG, ST.* FROM {search_table} ST) 
     WHERE FLAG = 1) A
     LEFT JOIN TURBINE_MASTER_TABLE TM ON A.COUNTRY_CD = TM.CODE
     LEFT JOIN OUTAGE_SCHEDULE C on A.TURBINE_ID = C.TURBINE_ID
     WHERE 1=1
     {and_sql})
     {where_sql}
'''

fetchOneTurbineSql = '''
    SELECT A.KHN_PLANT_CD AS PLANT_CD, NVL(A.PLANT_NAME_EN, A.PLANT_NAME_JP) AS PLANT_NAME,
      TM.DATA1 AS COUNTRY_NM, A.TURBINE_ID,A.DATA_TYPE
    FROM {search_table} A
    LEFT JOIN TURBINE_MASTER_TABLE TM ON A.COUNTRY_CD = TM.CODE
    WHERE TURBINE_ID = '{turbine_id}'
      AND DATA_TYPE = '{data_type}'
'''
