scheduleListCountSql = '''
    SELECT COUNT(DISTINCT A.TURBINE_ID) FROM 
        (SELECT * FROM
            ( SELECT ROW_NUMBER () OVER ( PARTITION BY TURBINE_ID ORDER BY DATA_TYPE DESC ) FLAG, ST.* FROM {search_table} ST) 
        WHERE FLAG = 1) A
    LEFT JOIN TURBINE_MASTER_TABLE TM ON A.COUNTRY_CD = TM.CODE
    LEFT JOIN OUTAGE_SCHEDULE C on A.TURBINE_ID = C.TURBINE_ID
    WHERE 1=1
    {and_sql}
'''

scheduleListSql = '''
    SELECT * FROM (
        SELECT A.KHN_PLANT_CD AS PLANT_CD, NVL(A.PLANT_NAME_EN, A.PLANT_NAME_JP) AS PLANT_NAME,
            TM.DATA1 AS COUNTRY_NM, A.TURBINE_ID,A.DATA_TYPE, C.OUTAGE_START, C.OUTAGE_END, C.TEIKEN_ID, C.DELETE_FLG,
            C.CREATED_AT,C.UPDATED_AT, C.CREATED_BY_NAME, C.UPDATED_BY_NAME, C.OUTAGE_TYPE_T, C.OUTAGE_TYPE_G,
            LEAST(NVL(C.OUTAGE_TYPE_T, 999), NVL(C.OUTAGE_TYPE_G, 999)) as COLOR_NUMBER,
            PKG_TURBINE_DB_UTIL.GET_TURBINE_DATA_URL(A.TURBINE_ID, '{session_id_in}') as DATA_URL,
            DENSE_RANK() OVER(ORDER BY A.TURBINE_ID, LEAST(NVL(C.OUTAGE_TYPE_T, 999), NVL(C.OUTAGE_TYPE_G, 999)) DESC) IDX
        FROM 
            (SELECT * FROM ( 
                 SELECT ROW_NUMBER () OVER ( PARTITION BY TURBINE_ID ORDER BY DATA_TYPE DESC ) FLAG, ST.*
                 FROM {search_table} ST) 
                 WHERE FLAG = 1
            ) A
        LEFT JOIN TURBINE_MASTER_TABLE TM ON A.COUNTRY_CD = TM.CODE
        LEFT JOIN OUTAGE_SCHEDULE C on A.TURBINE_ID = C.TURBINE_ID
        WHERE 1 = 1
        {and_sql}
        ORDER BY PLANT_NAME
    )
    {where_sql}
'''

fetchOneTurbineSql = '''
    SELECT A.KHN_PLANT_CD AS PLANT_CD, NVL(A.PLANT_NAME_EN, A.PLANT_NAME_JP) AS PLANT_NAME,
      TM.DATA1 AS COUNTRY_NM, A.TURBINE_ID, A.DATA_TYPE
    FROM {search_table} A
    LEFT JOIN TURBINE_MASTER_TABLE TM ON A.COUNTRY_CD = TM.CODE
    WHERE TURBINE_ID = '{turbine_id}'
      AND DATA_TYPE = '{data_type}'
'''

fetchRepresentiveSql = '''
    SELECT U.TUID AS REPRESENTIVE_ID , U.PERSON_FAMILY_NAME || ' ' || U.PERSON_FIRST_NAME AS REPRESENTIVE_NAME
    FROM SVCDB_USER_MASTER U
    WHERE EXISTS (
        SELECT 1 FROM SVCDB_USER_MASTER U2
        WHERE U2.TUID = '{tuid}'
        AND U2.MANAGEMENT_CORP_CD = U.MANAGEMENT_CORP_CD
        AND U2.DEPT_CD = U.DEPT_CD
    )
    UNION 
    SELECT S.REPRESENTIVE_ID, S.REPRESENTIVE_NAME
    FROM OUTAGE_SCHEDULE S
    WHERE S.TEIKEN_ID = '{teiken_id}'
    ORDER BY 2
'''

selectPlantByCountrySql = '''
    SELECT NVL(A.PLANT_NAME_EN, A.PLANT_NAME_JP) PLANT FROM {search_table} A
    LEFT JOIN TURBINE_MASTER_TABLE TM ON A.COUNTRY_CD = TM.CODE
    WHERE TM.MASTER_KIND = 'COUNTRY'
    AND A.COUNTRY_CD = '{country_cd}'
    GROUP BY NVL(A.PLANT_NAME_EN, A.PLANT_NAME_JP)
    ORDER BY NVL(A.PLANT_NAME_EN, A.PLANT_NAME_JP)
'''
